name: Workflow Call - Build Mod

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: release

      - name: Grab info
        id: info
        run: |
          VERSION=$(cat release/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.info.outputs.version }}
          tag: ${{ steps.info.outputs.version }}
          commit: ${{ github.ref }}
          artifacts: "*.zip"
          bodyFile: "body.md"
          makeLatest: true
