name: Push (main)

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-docker:
    uses: ./.github/workflows/_build-docker.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      project_name: valheim-vrm

  build-mod:
    needs: build-docker
    uses: ./.github/workflows/_build-mod.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      project_name: valheim-vrm

  publish:
    needs: build-mod
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    permissions:
      actions: read
      contents: write
